### PR TITLE
Fixes issue #9 - added unique event name "showandtell"

### PR DESCRIPTION
**Pull request by ViRuSTriNiTy**
... and updated tests (children.js still shows issues)

see issue #9

### CODE REVIEW

**Comment by hypesystem** [comment]
This looks pretty good. Are the tests still passing?

I think I might prefer the events to be namespaced, eg. `showandtell.remove` instead of `remove` (and also instead of your proposed `showandtell` with reason: remove). What do you think about that?

Thanks for taking the time to make a PR :-)

**Comment by ViRuSTriNiTy** [comment]
All tests are passing but i can't get `children.js` to work. Would you mind taking a look what`s the issue there? 

As for the namespaced event name, i initialy opted towards this solution but i found some issues with it like:

https://stackoverflow.com/questions/4718841/namespaced-custom-events-trigger

Maybe i should just try it out, perhaps this issue isn't there anymore.

**Comment by hypesystem** [comment]
Fair, let's go with the model for event naming you have implemented for now.

What output is children.js giving you?

**Comment by hypesystem** [comment]
Oh! I think maybe children.js never worked, so you're ok leaving it broken :-) (I know this is really bad practice, but it is as-yet unfixed...)

**Comment by hypesystem** [comment]
I will just merge your code :-)

**Comment by ViRuSTriNiTy** [comment]
Side note: i've tested namespace events with jQuery 2.1.4 and jQuery 3.0, seems to work properly, so the stackoverflow issue does not exist anymore.

**Comment by ViRuSTriNiTy** [comment]
Another side note: the `children.js` test was never working as you added these tests in an issue discussion, see here: https://github.com/hypesystem/showandtell.js/issues/7#issuecomment-34924762

**Comment by hypesystem** [comment]
Cool. I think maybe we should go for the namespaced events before we make a release, if there aren't any issues with them? What do you say?

**Comment by ViRuSTriNiTy** [comment]
Namespace incoming in PR #12, see also issue #11

**Pull request merged**
